config/routes.rb
Rails.application.routes.draw do
resources :tweets
  root 'pages#show', page: 'home'

  get '/pages/:page', to: 'pages#show'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    page = params[:page]
    render "pages/#{page}"
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all
    if params[:sort]
      @tweets = Tweet.order(params[:sort])

#   Tweet.order(:created_at)
#   Tweet.all.order. _____
  end
end

  def show

  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      flash[:success] = "Tweet succesfully created"
      redirect_to tweets_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @tweet.update_attributes(tweet_params)
      redirect_to tweets_path
    else
      render :edit
    end
  end

   def destroy
     @tweet.destroy
     redirect_to tweets_path
   end

  def sort
   @tweets.sort_by &:created_at
  end



  private
  def tweet_params
    params.require(:tweet).permit(:handle, :content)
  end

  def set_tweet
      @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="jumbotron text-center">
    <div class="container" >
    <h1 style="color: white"></h1>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

  </div>
</div>

<div>
<img class="avatar" src="https://c1.staticflickr.com/3/2693/4111117620_2945c576c4.jpg">
</div>



<nav class="navbar navbar-fixed-top navbar-light bg-faded">
  <a class="navbar-brand" href="#">
    <img src="https://g.twimg.com/blog/s200/twitter-bird.png" width="50" height="30" alt="">
  </a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to "Home", tweets_path %>
    </li>

  </ul>
</nav>


<div class="container">
<div class="col-4">
<div class="panel panel-default">
<div class="panel-heading">
</div>
    <div class="panel-body">
  <%= yield %>
      </div>
</div>
</div>
</div>



</body>
</html>

app/views/tweets/edit.html.erb
<h1>Edit</h1>

<%= form_for @tweet do |f| %>

    <div>
        <%= f.label :handle %>
        <%= f.text_field :handle %>
    </div>

    <div>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </div>

    <%= f.submit "Edit this Tweet" %>

<% end %>

<%= link_to "Back to all Tweets", tweets_path %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

<div>
<%= link_to "Sort by Date", :sort => 'created_at' %>
<br>
<%= link_to "Sort by Handle", :sort => 'Handle' %>
</div>
<br>
<div>
    <% @tweets.each do |tweet| %>
  <div class="panel-heading">
        <strong>Posted by <%= tweet.handle %> </strong>
        <%= time_ago_in_words(tweet.created_at.localtime) + " ago" %>
      </div>
    <div class="panel-body">
      <%= tweet.content %> <br>
        <p><%= link_to "Click to View Tweet", tweet_path(tweet) %></p>
        </div>
    <% end %>


<button type="button" class="btn btn-info">
<%= link_to "Post a new Tweet", new_tweet_path(@tweet) %>
</button>
<%#= tweet.created_at.strftime("Created on %m/%d/%Y" " at %I:%M%p") %>

</div>

app/views/tweets/new.html.erb
<h1>New</h1>

<%= form_for @tweet do |f| %>

    <div>
        <%= f.label :handle %>
        <%= f.text_field :handle %>
    </div>

    <div>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </div>


    <%= f.submit "Add new Tweet" %>

<% end %>

<%= link_to "Back to all Tweets", tweets_path %>

app/views/tweets/show.html.erb
<p><strong> <%= @tweet.handle %> </strong></p>
<p> <%= @tweet.content %></p>
<%= @tweet.created_at.localtime.strftime("Created on %m/%d/%Y" " at %I:%M%p") %>

<p><%= link_to "Edit this tweet.", edit_tweet_path(@tweet) %></p>

<br>

<%= link_to "DELETE this tweet!", tweet_path, method: :delete, data: { confirm: "Are you sure you want to delete this tweet?"} %>

<br>


<p><%= link_to "Go back to all tweets", tweets_path %></p>